name: Deploy website

on: 
    push:
        branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "**/package.json"
        
      - name: Install Netlify
        working-directory: ./planossa
        run: yarn add netlify-cli

      - name: Install Dependencies
        working-directory: ./planossa
        run: yarn install

      - name: Build project
        working-directory: ./planossa
        run: yarn build

      - name: Deploy to Netlify
        id: netlify_deploy
        working-directory: ./planossa
        run: |
          netlify deploy --prod \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
